export const mockJokes = [
  {
    id: 1,
    setup: "Why don't scientists trust atoms?",
    delivery: "Because they make up everything!",
    category: "Programming",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 2,
    setup: "Why did the scarecrow win an award?",
    delivery: "Because he was outstanding in his field!",
    category: "Misc",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 3,
    joke: "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    category: "Misc",
    type: "single",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 4,
    setup: "Pourquoi les plongeurs plongent-ils toujours en arrière et jamais en avant?",
    delivery: "Parce que sinon, ils tombent dans le bateau!",
    category: "Misc",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "fr",
    safe: true,
  },
  {
    id: 5,
    joke: "Que dit un escargot quand il croise une limace? Regardez-moi ce nudiste!",
    category: "Misc",
    type: "single",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "fr",
    safe: true,
  },
  {
    id: 6,
    setup: "Warum nehmen Seeräuber keinen Kreis?",
    delivery: "Weil sie Pi raten!",
    category: "Programming",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "de",
    safe: true,
  },
  {
    id: 7,
    joke: "Was ist grün und klopft an der Tür? Ein Klopfsalat!",
    category: "Misc",
    type: "single",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "de",
    safe: true,
  },
  {
    id: 8,
    setup: "Why do programmers prefer dark mode?",
    delivery: "Because light attracts bugs!",
    category: "Programming",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 9,
    joke: "There are only 10 types of people in the world: those who understand binary and those who don't.",
    category: "Programming",
    type: "single",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 10,
    setup: "Why don't scientists trust stairs?",
    delivery: "Because they're always up to something!",
    category: "Misc",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 11,
    joke: "I'm reading a book on anti-gravity. It's impossible to put down!",
    category: "Pun",
    type: "single",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 12,
    setup: "Que dit un café qui rentre chez lui?",
    delivery: "Je rentre à la maison!",
    category: "Pun",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "fr",
    safe: true,
  },
  {
    id: 13,
    setup: "Pourquoi les poissons n'aiment pas jouer au tennis?",
    delivery: "Parce qu'ils ont peur du filet!",
    category: "Misc",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "fr",
    safe: true,
  },
  {
    id: 14,
    joke: "Comment appelle-t-on un chat tombé dans un pot de peinture le jour de Noël? Un chat-mallow!",
    category: "Pun",
    type: "single",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "fr",
    safe: true,
  },
  {
    id: 15,
    setup: "Pourquoi les développeurs préfèrent-ils le mode sombre?",
    delivery: "Parce que la lumière attire les bugs!",
    category: "Programming",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "fr",
    safe: true,
  },
  {
    id: 16,
    setup: "Was ist der Unterschied zwischen einem Informatiker und einem normalen Menschen?",
    delivery: "Der Informatiker denkt, dass es nur 10 Arten von Menschen gibt!",
    category: "Programming",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "de",
    safe: true,
  },
  {
    id: 17,
    joke: "Warum können Geister so schlecht lügen? Weil man durch sie hindurchsehen kann!",
    category: "Misc",
    type: "single",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "de",
    safe: true,
  },
  {
    id: 18,
    setup: "Was sagt ein großer Stift zum kleinen Stift?",
    delivery: "Wachs-mal-stift!",
    category: "Pun",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "de",
    safe: true,
  },
  {
    id: 19,
    joke: "Treffen sich zwei Magnete. Sagt der eine: 'Was machst du heute Abend?' Sagt der andere: 'Nichts Besonderes.' Sagt der erste: 'Dann lass uns zusammen hängen!'",
    category: "Misc",
    type: "single",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "de",
    safe: true,
  },
  {
    id: 20,
    setup: "Why did the function break up with the variable?",
    delivery: "Because it wasn't returning the same value!",
    category: "Programming",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 21,
    joke: "How many programmers does it take to change a light bulb? None, that's a hardware problem!",
    category: "Programming",
    type: "single",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 22,
    setup: "What do you call a programmer from Finland?",
    delivery: "Nerdic!",
    category: "Programming",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
];

// Debug: Log available languages in mock data
console.log("📚 Mock Data Languages Available:");
const languageCount = mockJokes.reduce((acc, joke) => {
  acc[joke.lang] = (acc[joke.lang] || 0) + 1;
  return acc;
}, {} as Record<string, number>);
console.log(languageCount);
