export const mockJokes = [
  {
    id: 1,
    setup: "Why don't scientists trust atoms?",
    delivery: "Because they make up everything!",
    category: "Programming",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 2,
    setup: "Why did the scarecrow win an award?",
    delivery: "Because he was outstanding in his field!",
    category: "Misc",
    type: "twopart",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
  {
    id: 3,
    joke: "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    category: "Misc",
    type: "single",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    lang: "en",
    safe: true,
  },
];
